### ISSUE TITLE
Error running the sample dataset

### ISSUE THREAD

**Issue by Pombert-JF** [thiesgehrmann/proteny#4]
I'm encountering issues running the sample dataset; I get the following error message below when I type the provided command line from the README. Looks like an issue with the fasta.py wrapper from ibidas. Any idea how to fix/circumvent this?

Thanks,
Jean-Francois Pombert
Illinois Tech, Chicago, IL

#####
RUNNING PROTENY
WARNING:root:Could not determine FASTA separator. Please specify through sep parameter
WARNING:root:Could not determine FASTA separator. Please specify through sep parameter
[5645, 5572]
Running BLAST for Cglabrata v Zrouxii
(a_chrid=bytes, a_start=int64, a_end=int64, a_strand=bytes, a_geneid=bytes, a_transcriptid=bytes, a_exonid=int64, a_sequence=protein)
(b_chrid=bytes, b_start=int64, b_end=int64, b_strand=bytes, b_geneid=bytes, b_transcriptid=bytes, b_exonid=int64, b_sequence=protein)
...
BLAST Database creation error: FASTA-Reader: No residues given
ERROR: Failed in cmd: makeblastdb -in '/tmp/tmpgimE45' -out '/tmp/tmpgimE45.blastdb' -dbtype 'prot'
ERROR: Failed in cmd: makeblastdb -in '/tmp/tmpHCFchE' -out '/tmp/tmpHCFchE.blastdb' -dbtype 'prot'

**Comment by thiesgehrmann** [comment]
Hello Jean-Francois,

Thanks for reporting this issue.
Unfortunately this seems to be a common problem, which I can't find the solution to. It seems to be a problem with a version dependency of ibidas, numpy and ipython. I should make some time to investigate this. I am really sorry that I can't help you at this time.

Best,
Thies

**Comment by thiesgehrmann** [comment]
Hello Jean-Francois,

I have re-implemented Proteny, removing a lot of dependencies, including ibidas.
This makes the pipeline much more simple and portable.
If you are still interested in trying proteny, you can find the re-implementation at: https://github.com/thiesgehrmann/pty

Thank you,
-Thies
